namespace Custom_keyboard.Localization;

/// <summary>
/// Central bilingual string table. Each entry holds the Vietnamese and English text side by side so
/// the two languages stay in sync and are easy to review. Look-ups go through <see cref="Loc"/>.
/// A missing key returns the key itself, which makes gaps obvious during development.
///
/// Key naming convention: &lt;Area&gt;_&lt;Name&gt; — e.g. Login_Title, Buyer_SaveBuild, Status_Completed.
/// </summary>
public static class AppStrings
{
    public static string Get(string key, AppLanguage language)
        => Table.TryGetValue(key, out var pair)
            ? (language == AppLanguage.Vietnamese ? pair.Vi : pair.En)
            : key;

    // (Vietnamese, English)
    private static readonly Dictionary<string, (string Vi, string En)> Table = new(StringComparer.Ordinal)
    {
        // ===== Common / shared =====
        ["Common_AppTitle"] = ("Trình build bàn phím tùy chỉnh", "Custom Keyboard Builder"),
        ["Common_AppName"] = ("CK Builder", "CK Builder"),
        ["Common_AppTagline"] = ("Bàn phím tùy chỉnh", "Custom Keyboard"),
        ["Common_Username"] = ("Tên đăng nhập", "Username"),
        ["Common_Email"] = ("Email", "Email"),
        ["Common_Phone"] = ("Số điện thoại", "Phone"),
        ["Common_Password"] = ("Mật khẩu", "Password"),
        ["Common_Role"] = ("Vai trò", "Role"),
        ["Common_Admin"] = ("Admin", "Admin"),
        ["Common_Seller"] = ("Seller", "Seller"),
        ["Common_Environment"] = ("WPF + SQL Server + Auth", "WPF + SQL Server + Auth"),
        ["Common_NotSignedIn"] = ("Chưa đăng nhập", "Not signed in"),
        ["Common_Status"] = ("Trạng thái", "Status"),
        ["Common_Refresh"] = ("Làm mới", "Refresh"),
        ["Common_Processing"] = ("Đang xử lý...", "Processing..."),
        ["Common_Ready"] = ("Sẵn sàng.", "Ready."),
        ["Common_Done"] = ("Hoàn tất.", "Done."),
        ["Common_Online"] = ("Trực tuyến", "Online"),
        ["Common_New"] = ("Mới", "New"),
        ["Common_Verified"] = ("Đã verify", "Verified"),
        ["Common_Unverified"] = ("Chưa verify", "Unverified"),
        ["Common_Active"] = ("Đang hoạt động", "Active"),
        ["Common_Inactive"] = ("Ngưng hoạt động", "Inactive"),
        ["Common_Banned"] = ("Đã khóa", "Banned"),
        ["Common_Available"] = ("Có", "Available"),
        ["Common_Hidden"] = ("Ẩn", "Hidden"),
        ["Common_You"] = ("Bạn", "You"),

        // ===== Status enums (key = Status_<EnumValue>) =====
        ["Status_Pending"] = ("Đang chờ", "Pending"),
        ["Status_Accepted"] = ("Đã nhận", "Accepted"),
        ["Status_In_progress"] = ("Đang thực hiện", "In progress"),
        ["Status_Completed"] = ("Hoàn thành", "Completed"),
        ["Status_Cancelled"] = ("Đã hủy", "Cancelled"),
        ["Status_Draft"] = ("Nháp", "Draft"),
        ["Status_Saved"] = ("Đã lưu", "Saved"),
        ["Status_Requested"] = ("Đã gửi yêu cầu", "Requested"),
        ["Status_Archived"] = ("Đã lưu trữ", "Archived"),
        ["Status_Approved"] = ("Đã duyệt", "Approved"),
        ["Status_Rejected"] = ("Đã từ chối", "Rejected"),
        // Device QC session status + per-key result
        ["Status_Running"] = ("Đang chạy", "Running"),
        ["Status_Passed"] = ("Đạt", "Passed"),
        ["Status_Warning"] = ("Cảnh báo", "Warning"),
        ["Status_Failed"] = ("Không đạt", "Failed"),
        ["Status_Pass"] = ("Đạt", "Pass"),
        ["Status_Fail"] = ("Lỗi", "Fail"),

        // ===== Device QC test (key =QcTest_<Name>) =====
        ["QcTest_NavQc"] = ("Kiểm tra QC", "QC Test"),
        ["QcTest_Title"] = ("Kiểm tra QC bàn phím", "Keyboard QC Test"),
        ["QcTest_StartHint"] = (
            "Chọn một yêu cầu đang 'Đang thực hiện' rồi bấm Bắt đầu để chạy mô phỏng QC.",
            "Select an 'In progress' request, then press Start to run the QC simulation."),
        ["QcTest_Start"] = ("Bắt đầu kiểm tra QC", "Start QC Test"),
        ["QcTest_Completed"] = ("Đã chạy xong kiểm tra QC.", "QC test completed."),
        ["QcTest_Summary"] = ("Tổng kết QC", "QC Summary"),
        ["QcTest_PerKey"] = ("Kết quả từng phím", "Per-key Results"),
        ["QcTest_NoData"] = ("Chưa có dữ liệu QC cho yêu cầu này.", "No QC data for this request yet."),
        ["QcTest_Tested"] = ("Đã test", "Tested"),
        ["QcTest_Passed"] = ("Đạt", "Passed"),
        ["QcTest_Warning"] = ("Cảnh báo", "Warning"),
        ["QcTest_Failed"] = ("Không đạt", "Failed"),
        ["QcTest_AvgLatency"] = ("Độ trễ TB (ms)", "Avg latency (ms)"),
        ["QcTest_MaxLatency"] = ("Độ trễ tối đa (ms)", "Max latency (ms)"),
        ["QcTest_AvgNoise"] = ("Độ ồn TB (dB)", "Avg noise (dB)"),
        ["QcTest_MaxNoise"] = ("Độ ồn tối đa (dB)", "Max noise (dB)"),
        ["QcTest_ColKey"] = ("Phím", "Key"),
        ["QcTest_ColPress"] = ("Press", "Press"),
        ["QcTest_ColRelease"] = ("Release", "Release"),
        ["QcTest_ColPressEvents"] = ("Số press", "Press events"),
        ["QcTest_ColBounce"] = ("Bounce", "Bounce"),
        ["QcTest_ColLatency"] = ("Độ trễ (ms)", "Latency (ms)"),
        ["QcTest_ColStuck"] = ("Kẹt", "Stuck"),
        ["QcTest_ColResult"] = ("Kết quả", "Result"),
        ["QcTest_ColFailureType"] = ("Loại lỗi", "Failure type"),
        ["QcTest_ColReason"] = ("Lý do", "Reason"),

        // ===== Login =====
        ["Login_Title"] = ("Đăng nhập", "Sign in"),
        ["Login_Subtitle"] = ("Đăng nhập để tiếp tục", "Sign in to continue"),
        ["Login_EmailOrUsername"] = ("Email hoặc tên đăng nhập", "Email or username"),
        ["Login_SignIn"] = ("Đăng nhập", "Sign in"),
        ["Login_CreateBuyerAccount"] = ("Tạo tài khoản buyer", "Create a buyer account"),
        ["Login_QuickTitle"] = ("Đăng nhập nhanh", "Quick login"),
        ["Login_QuickSubtitle"] = ("Tài khoản seed dùng chung mật khẩu Password123.", "Seed accounts use the shared Password123 password."),

        // ===== Register =====
        ["Register_Title"] = ("Đăng ký buyer", "Buyer sign up"),
        ["Register_Subtitle"] = ("Tạo tài khoản để bắt đầu build keyboard", "Create an account to start building keyboards"),
        ["Register_ConfirmPassword"] = ("Xác nhận mật khẩu", "Confirm password"),
        ["Register_Submit"] = ("Đăng ký", "Sign up"),
        ["Register_BackToLogin"] = ("Quay lại đăng nhập", "Back to sign in"),

        // ===== Validation (client side) =====
        ["Validation_PasswordMismatch"] = ("Mật khẩu xác nhận không khớp.", "Passwords do not match."),

        // ===== Account service messages =====
        ["Account_LoginEmpty"] = ("Nhập email/username và mật khẩu.", "Enter your email/username and password."),
        ["Account_InvalidCredentials"] = ("Email/username hoặc mật khẩu không đúng.", "Incorrect email/username or password."),
        ["Account_Inactive"] = ("Tài khoản đang bị khóa.", "This account is locked."),
        ["Account_RegisterEmpty"] = ("Nhập đầy đủ username, email, phone và mật khẩu.", "Enter username, email, phone and password."),
        ["Account_PasswordTooShort"] = ("Mật khẩu cần ít nhất 6 ký tự.", "Password must be at least 6 characters."),
        ["Account_EmailInvalid"] = ("Email không đúng định dạng (vd: ten@domain.com).", "Invalid email format (e.g. name@domain.com)."),
        ["Account_PhoneInvalid"] = ("Số điện thoại không hợp lệ (8-15 chữ số, có thể bắt đầu bằng +).", "Invalid phone number (8-15 digits, optional leading +)."),
        ["Account_DuplicateUsername"] = ("Tên đăng nhập đã tồn tại.", "Username already exists."),
        ["Account_DuplicateEmail"] = ("Email đã tồn tại.", "Email already exists."),
        ["Account_DuplicatePhone"] = ("Số điện thoại đã tồn tại.", "Phone already exists."),
        ["Account_RegisterSuccess"] = ("Đăng ký thành công. Hãy đăng nhập.", "Registration successful. Please sign in."),
        ["Account_LoggedOut"] = ("Đã đăng xuất.", "Signed out."),

        // ===== Chat =====
        ["Chat_Title"] = ("Hội thoại", "Conversations"),
        ["Chat_SelectSeller"] = ("Chọn seller để chat", "Select a seller to chat"),
        ["Chat_OpenWithSeller"] = ("Mở hội thoại với seller", "Open conversation with seller"),
        ["Chat_EmptyConvTitle"] = ("Chưa có hội thoại", "No conversations"),
        ["Chat_EmptyConvText"] = ("Mở hội thoại với seller hoặc chờ tin nhắn mới xuất hiện tại đây.", "Open a conversation with a seller, or wait for new messages to appear here."),
        ["Chat_RefreshConversations"] = ("Làm mới hội thoại", "Refresh conversations"),
        ["Chat_EmptyMsgTitle"] = ("Chưa có tin nhắn", "No messages"),
        ["Chat_EmptyMsgText"] = ("Chọn hội thoại và gửi tin nhắn đầu tiên.", "Select a conversation and send the first message."),
        ["Chat_Send"] = ("Gửi", "Send"),
        ["Chat_RefreshedConversations"] = ("Đã làm mới hội thoại.", "Conversations refreshed."),
        ["Chat_MessageSent"] = ("Đã gửi tin nhắn.", "Message sent."),
        ["Chat_RefreshedMessages"] = ("Đã làm mới tin nhắn.", "Messages refreshed."),
        ["Chat_SelectSellerFirst"] = ("Chọn seller trước.", "Select a seller first."),
        ["Chat_SelectConversationFirst"] = ("Chọn hội thoại trước.", "Select a conversation first."),
        ["Chat_ConversationOpened"] = ("Đã mở hội thoại.", "Conversation opened."),
        ["Chat_UpdatedAt"] = ("Cập nhật: {0:yyyy-MM-dd HH:mm}", "Updated: {0:yyyy-MM-dd HH:mm}"),
        ["Chat_BuyerFallback"] = ("Buyer #{0}", "Buyer #{0}"),
        ["Chat_AdminFallback"] = ("Admin #{0}", "Admin #{0}"),
        ["Chat_SellerFallback"] = ("Seller #{0}", "Seller #{0}"),
        ["Chat_UserFallback"] = ("User #{0}", "User #{0}"),

        // ===== User menu (top-right dropdown) =====
        ["UserMenu_ProfileSettings"] = ("Hồ sơ tài khoản", "Profile settings"),
        ["UserMenu_ProfileTooltip"] = ("Xem thông tin hồ sơ tài khoản hiện tại", "View the current account profile"),
        ["UserMenu_AccountProfile"] = ("Hồ sơ tài khoản", "Account profile"),
        ["UserMenu_RoleLabel"] = ("Vai trò:", "Role:"),
        ["UserMenu_UserIdLabel"] = ("Mã người dùng:", "User ID:"),
        ["UserMenu_ViewOnlyNote"] = ("Chỉ xem trong đợt này; cập nhật hồ sơ/tài khoản sẽ tách sang Cài đặt tài khoản.", "View-only for now; profile/account updates will move to Account settings."),
        ["UserMenu_AccountSettings"] = ("Cài đặt tài khoản", "Account settings"),
        ["UserMenu_AccountSettingsTooltip"] = ("Chưa có màn hình tùy chỉnh tài khoản", "Account settings screen is not available yet"),
        ["UserMenu_Preferences"] = ("Tùy chọn", "Preferences"),
        ["UserMenu_PreferencesTooltip"] = ("Chọn ngôn ngữ hiển thị", "Choose the display language"),
        ["UserMenu_Language"] = ("Ngôn ngữ", "Language"),
        ["UserMenu_LanguageVietnamese"] = ("Tiếng Việt", "Tiếng Việt"),
        ["UserMenu_LanguageEnglish"] = ("English", "English"),
        ["UserMenu_Logout"] = ("Đăng xuất", "Sign out"),

        // ===== Common additions (shared across dashboards) =====
        ["Common_General"] = ("Chung", "General"),
        ["Common_DaysUnit"] = ("ngày", "days"),
        ["Common_Notes"] = ("Ghi chú", "Notes"),
        ["Common_Address"] = ("Địa chỉ", "Address"),
        ["Common_ShopName"] = ("Tên shop", "Shop name"),
        ["Nav_Chat"] = ("Chat", "Chat"),
        ["Common_DaysFormat"] = ("{0:N1} ngày", "{0:N1} days"),
        // DataGrid column headers (uppercase to match the table styling)
        ["Common_ColRequest"] = ("REQUEST", "REQUEST"),
        ["Common_ColBuild"] = ("BUILD", "BUILD"),
        ["Common_ColSeller"] = ("SELLER", "SELLER"),
        ["Common_ColStatus"] = ("TRẠNG THÁI", "STATUS"),
        ["Common_ColUsername"] = ("TÊN ĐĂNG NHẬP", "USERNAME"),
        ["Common_ColEmail"] = ("EMAIL", "EMAIL"),
        ["Common_ColRole"] = ("VAI TRÒ", "ROLE"),
        ["Common_ColShop"] = ("SHOP", "SHOP"),
        ["Common_ColDate"] = ("NGÀY", "DATE"),

        // ===== Buyer dashboard (ViewModel-produced) =====
        ["Buyer_Title"] = ("Bảng điều khiển Buyer", "Buyer dashboard"),
        ["Buyer_Subtitle"] = ("Chọn kit, thêm linh kiện và gửi request cho seller.", "Pick a kit, add parts, and send a request to a seller."),
        ["Buyer_Task1"] = ("Chọn kit và thêm switch/keycap/stabilizer/accessory", "Pick a kit and add switch/keycap/stabilizer/accessory"),
        ["Buyer_Task2"] = ("Xem cảnh báo tương thích và tổng giá", "Review compatibility warnings and the total price"),
        ["Buyer_Task3"] = ("Lưu build và gửi request cho seller", "Save the build and send a request to a seller"),
        ["Buyer_Task4"] = ("Theo dõi trạng thái request và chat", "Track request status and chat"),
        ["Buyer_Refreshed"] = ("Đã làm mới bảng điều khiển buyer.", "Buyer dashboard refreshed."),
        ["Buyer_BuildArchived"] = ("Đã lưu trữ build.", "Build archived."),
        ["Buyer_NoSellers"] = ("Chưa có seller active/verified để nhận request.", "No active/verified sellers available to take requests."),
        ["Buyer_NoKitSelected"] = ("Chưa chọn kit.", "No kit selected."),
        ["Buyer_KitSummaryFormat"] = ("{0} / mount {1} / cần {2} switch", "{0} / mount {1} / needs {2} switches"),
        ["Buyer_KitIncludes"] = ("\nGồm: {0}", "\nIncludes: {0}"),
        ["Buyer_NoApplication"] = ("Bạn chưa nộp đơn đăng ký seller.", "You haven't submitted a seller application yet."),
        ["Buyer_ApplicationStatusFormat"] = ("Trạng thái đơn: {0}", "Application status: {0}"),
        ["Buyer_ApplicationSubmitted"] = ("Đã gửi đơn đăng ký seller. Vui lòng chờ admin duyệt.", "Seller application submitted. Please wait for admin approval."),
        ["Buyer_RealtimeUpdate"] = ("Có cập nhật trạng thái request (realtime).", "Request status updated (realtime)."),
        ["Buyer_BuildSaved"] = ("Đã lưu build '{0}' - tổng {1:F2} USD.", "Saved build '{0}' - total {1:F2} USD."),
        ["Buyer_SelectBuildFirst"] = ("Chọn build trước.", "Select a build first."),
        ["Buyer_SelectSavedBuildFirst"] = ("Chọn build đã lưu trước khi gửi request.", "Select a saved build before sending a request."),
        ["Buyer_SelectSellerFirst"] = ("Chọn seller trước khi gửi request.", "Select a seller before sending a request."),
        ["Buyer_RequestSent"] = ("Đã gửi request {0} cho {1}.", "Sent request {0} to {1}."),
        ["Buyer_BuildLoaded"] = ("Đã nạp build vào configurator.", "Build loaded into the configurator."),
        ["Buyer_NewBuildPrompt"] = ("Nhập cấu hình build mới.", "Enter the new build configuration."),
        ["Buyer_ModQuantityFull"] = ("Tổng số switch cho mod {0} đã bằng số switch của build.", "Total switches for mod {0} already equals the build's switch count."),
        ["Buyer_ModNoNotes"] = ("Chưa có ghi chú.", "No notes."),

        // ===== Buyer dashboard (XAML labels) =====
        ["Buyer_Workspace"] = ("Không gian Buyer", "Buyer workspace"),
        ["Buyer_NavHome"] = ("Trang chủ", "Home"),
        ["Buyer_NavMyBuilds"] = ("Build của tôi", "My builds"),
        ["Buyer_NavNewBuild"] = ("Tạo build mới", "New build"),
        ["Buyer_NavSentRequests"] = ("Request đã gửi", "Sent requests"),
        ["Buyer_NavRegisterSeller"] = ("Đăng ký Seller", "Become a seller"),
        ["Buyer_Workflow"] = ("Quy trình buyer", "Buyer workflow"),
        ["Buyer_NewBuildPlus"] = ("+ Tạo build mới", "+ New build"),
        ["Buyer_ColBuildName"] = ("TÊN BUILD", "BUILD NAME"),
        ["Buyer_ColKit"] = ("KIT", "KIT"),
        ["Buyer_ColTotal"] = ("TỔNG (USD)", "TOTAL (USD)"),
        ["Buyer_EmptyBuildsTitle"] = ("Chưa có build nào", "No builds yet"),
        ["Buyer_EmptyBuildsText"] = ("Bấm Tạo build mới để tạo cấu hình đầu tiên.", "Click New build to create your first configuration."),
        ["Buyer_OpenInConfigurator"] = ("Mở trong configurator", "Open in configurator"),
        ["Buyer_Archive"] = ("Lưu trữ", "Archive"),
        ["Buyer_ConfigTitle"] = ("Cấu hình build", "Build configuration"),
        ["Buyer_BuildNameLabel"] = ("Tên build", "Build name"),
        ["Buyer_NoiseRequirementLabel"] = ("Yêu cầu độ ồn", "Noise requirement"),
        ["Buyer_KitLabel"] = ("Kit", "Kit"),
        ["Buyer_SwitchLabel"] = ("Switch", "Switch"),
        ["Buyer_UseKitQuantity"] = ("Dùng số lượng kit", "Use kit quantity"),
        ["Buyer_SwitchQuantityLabel"] = ("Số lượng switch", "Switch quantity"),
        ["Buyer_KeycapLabel"] = ("Keycap", "Keycap"),
        ["Buyer_StabilizerLabel"] = ("Stabilizer", "Stabilizer"),
        ["Buyer_AccessoryLabel"] = ("Accessory", "Accessory"),
        ["Buyer_RemoveSelectedMod"] = ("Xóa mod đang chọn", "Remove selected mod"),
        ["Buyer_ModPresets"] = ("Mod presets", "Mod presets"),
        ["Buyer_ModPresetSwitchLube"] = ("Lube switch", "Switch lube"),
        ["Buyer_ModPresetSwitchFilm"] = ("Film switch", "Switch film"),
        ["Buyer_ModPresetSpringSwap"] = ("Thay spring", "Spring swap"),
        ["Buyer_ModPresetStabLube"] = ("Lube stab", "Stab lube"),
        ["Buyer_ModPresetStabTune"] = ("Tune stab", "Stab tune"),
        ["Buyer_ModPresetTapeMod"] = ("Tape mod", "Tape mod"),
        ["Buyer_ModPresetFoamMod"] = ("Foam mod", "Foam mod"),
        ["Buyer_ModTargetSwitch"] = ("Switch", "Switch"),
        ["Buyer_ModTargetStabilizer"] = ("Stabilizer", "Stabilizer"),
        ["Buyer_ModTargetBuild"] = ("Build", "Build"),
        ["Buyer_ModTargetKit"] = ("Kit", "Kit"),
        ["Buyer_ModTypeLube"] = ("Lube", "Lube"),
        ["Buyer_ModTypeFilm"] = ("Film", "Film"),
        ["Buyer_ModTypeSpring_swap"] = ("Thay spring", "Spring swap"),
        ["Buyer_ModTypeTune"] = ("Tune", "Tune"),
        ["Buyer_ModTypeHolee_mod"] = ("Holee mod", "Holee mod"),
        ["Buyer_ModTypeTape_mod"] = ("Tape mod", "Tape mod"),
        ["Buyer_ModTypeFoam_mod"] = ("Foam mod", "Foam mod"),
        ["Buyer_ModSwitchQuantitySummary"] = ("{0} switch", "{0} switches"),
        ["Buyer_ModTarget"] = ("Target", "Target"),
        ["Buyer_ModType"] = ("Mod type", "Mod type"),
        ["Buyer_ModSwitchCount"] = ("Số switch", "Switches"),
        ["Buyer_ModGram"] = ("Gram", "Gram"),
        ["Buyer_ModNotesTooltip"] = ("Ghi chú tùy chọn, ví dụ Krytox 205g0, TX films, 2 layers tape...", "Optional notes, e.g. Krytox 205g0, TX films, 2 layers tape..."),
        ["Buyer_TotalSnapshotLabel"] = ("TỔNG GIÁ (SNAPSHOT)", "TOTAL PRICE (SNAPSHOT)"),
        ["Buyer_SaveBuild"] = ("Lưu build", "Save build"),
        ["Buyer_SendRequestSection"] = ("Gửi request cho seller", "Send a request to a seller"),
        ["Buyer_SellerReputation"] = ("Uy tín seller", "Seller reputation"),
        ["Buyer_SellerProductsMade"] = ("Sản phẩm đã làm", "Products made"),
        ["Buyer_SellerTotalOrders"] = ("Tổng đơn nhận", "Total orders"),
        ["Buyer_SellerCustomers"] = ("Khách đã phục vụ", "Customers served"),
        ["Buyer_SellerAvgCompletion"] = ("TB hoàn thành", "Avg. completion"),
        ["Buyer_SellerMemberSince"] = ("Thành viên từ", "Member since"),
        ["Buyer_SendRequest"] = ("Gửi request", "Send request"),
        ["Buyer_BecomeSellerTitle"] = ("Đăng ký trở thành Seller", "Apply to become a seller"),
        ["Buyer_BecomeSellerDesc"] = ("Gửi thông tin shop để admin duyệt. Khi được duyệt, bạn sẽ thành Seller (đã verify) và đăng nhập lại để vào dashboard seller.", "Submit your shop details for admin approval. Once approved you become a verified seller; sign in again to open the seller dashboard."),
        ["Buyer_NoteOptional"] = ("Ghi chú (không bắt buộc)", "Notes (optional)"),
        ["Buyer_SubmitApplication"] = ("Gửi đơn đăng ký", "Submit application"),
        ["Buyer_EmptyRequestsTitle"] = ("Chưa gửi request nào", "No requests sent yet"),
        ["Buyer_EmptyRequestsText"] = ("Lưu build và chọn seller đã verify để gửi request.", "Save a build and pick a verified seller to send a request."),

        // ===== Legacy main view model =====
        ["Main_Environment"] = ("WPF + SQL Server ready structure", "WPF + SQL Server ready structure"),
        ["Main_BuyerTask1"] = ("Đăng nhập/đăng ký tài khoản buyer", "Sign in/sign up for a buyer account"),
        ["Main_BuyerTask2"] = ("Tra cứu danh mục linh kiện và rule tương thích", "Browse component catalog and compatibility rules"),
        ["Main_BuyerTask3"] = ("Tạo cấu hình build keyboard", "Create a keyboard build configuration"),
        ["Main_BuyerTask4"] = ("Tính tổng giá snapshot", "Calculate the total price snapshot"),
        ["Main_BuyerTask5"] = ("Lưu build và gửi request cho seller", "Save the build and send a request to a seller"),
        ["Main_BuyerTask6"] = ("Theo dõi trạng thái request", "Track request status"),
        ["Main_SellerTask1"] = ("Đăng nhập tài khoản seller", "Sign in with a seller account"),
        ["Main_SellerTask2"] = ("Xem danh sách request được gán", "View assigned requests"),
        ["Main_SellerTask3"] = ("Mở chi tiết build snapshot", "Open build snapshot details"),
        ["Main_SellerTask4"] = ("Cập nhật trạng thái Accepted/In_progress/Completed/Cancelled", "Update Accepted/In_progress/Completed/Cancelled status"),
        ["Main_AdminTask1"] = ("Đăng nhập tài khoản admin", "Sign in with an admin account"),
        ["Main_AdminTask2"] = ("Quản lý user và role", "Manage users and roles"),
        ["Main_AdminTask3"] = ("Quản lý seller profile và verify seller", "Manage seller profiles and seller verification"),
        ["Main_AdminTask4"] = ("Quản lý danh mục linh kiện", "Manage the component catalog"),
        ["Main_AdminTask5"] = ("Xem audit log", "Review audit log"),

        // ===== Build validation (BuildService) =====
        ["Build_NotExist"] = ("Build không tồn tại.", "Build does not exist."),
        ["Build_NotOwned"] = ("Build không thuộc buyer hiện tại.", "This build does not belong to the current buyer."),
        ["Build_InvalidBuyer"] = ("Buyer không hợp lệ.", "Invalid buyer."),
        ["Build_NameRequired"] = ("Nhập tên build trước khi lưu.", "Enter a build name before saving."),
        ["Build_NotesTooLong"] = ("Ghi chú không được vượt quá {0} ký tự.", "Notes may not exceed {0} characters."),
        ["Build_LayoutMissing"] = ("Không tìm thấy layout của kit; bỏ qua kiểm tra form factor.", "Kit layout not found; skipping the form-factor check."),
        ["Build_ItemOneProduct"] = ("Mỗi build item phải chọn đúng một sản phẩm (switch/keycap/stab/accessory).", "Each build item must select exactly one product (switch/keycap/stab/accessory)."),
        ["Build_ItemQuantityPositive"] = ("Số lượng build item phải lớn hơn 0.", "Build item quantity must be greater than 0."),
        ["Build_SwitchQuantityShort"] = ("Kit cần ít nhất {0} switch, hiện chỉ có {1}.", "The kit needs at least {0} switches, currently only {1}."),
        ["Build_NoKeycap"] = ("Build chưa có keycap set.", "Build has no keycap set yet."),
        ["Build_NoStabilizer"] = ("Build chưa có stabilizer.", "Build has no stabilizer yet."),
        ["Build_TotalInfo"] = ("Tổng tiền: {0:0.00} USD.", "Total: {0:0.00} USD."),
        ["Build_SwitchToBuyInfo"] = ("Số switch cần mua: {0}.", "Switches to buy: {0}."),
        ["Build_KitIncludesInfo"] = ("Kit đã gồm: {0}.", "Kit already includes: {0}."),
        ["Build_KitRequired"] = ("Chọn kit trước khi lưu build.", "Select a kit before saving the build."),
        ["Build_KitNotExist"] = ("Kit đã chọn không tồn tại.", "The selected kit does not exist."),
        ["Build_KitUnavailable"] = ("Kit đã chọn không còn khả dụng.", "The selected kit is no longer available."),
        ["Build_KitMissingInfo"] = ("Kit thiếu thông tin pcb technology / switch mount.", "Kit is missing pcb technology / switch mount info."),
        ["Build_KitPriceInvalid"] = ("Giá kit không hợp lệ.", "Invalid kit price."),
        ["Build_SwitchNotExist"] = ("Switch '{0}' không tồn tại.", "Switch '{0}' does not exist."),
        ["Build_SwitchUnavailable"] = ("Switch '{0}' không còn khả dụng.", "Switch '{0}' is no longer available."),
        ["Build_SwitchTechMismatch"] = ("Switch technology '{0}' không khớp kit '{1}'.", "Switch technology '{0}' does not match kit '{1}'."),
        ["Build_SwitchMountMismatch"] = ("Switch mount '{0}' không khớp kit '{1}'.", "Switch mount '{0}' does not match kit '{1}'."),
        ["Build_KeycapNotExist"] = ("Keycap '{0}' không tồn tại.", "Keycap '{0}' does not exist."),
        ["Build_KeycapUnavailable"] = ("Keycap '{0}' không còn khả dụng.", "Keycap '{0}' is no longer available."),
        ["Build_KeycapFormFactorWarn"] = ("Keycap '{0}' có thể không phù hợp form factor '{1}'.", "Keycap '{0}' may not fit form factor '{1}'."),
        ["Build_StabilizerNotExist"] = ("Stabilizer '{0}' không tồn tại.", "Stabilizer '{0}' does not exist."),
        ["Build_StabilizerUnavailable"] = ("Stabilizer '{0}' không còn khả dụng.", "Stabilizer '{0}' is no longer available."),
        ["Build_StabilizerLayoutWarn"] = ("Stabilizer '{0}' có thể không phù hợp layout '{1}'.", "Stabilizer '{0}' may not fit layout '{1}'."),
        ["Build_AccessoryNotExist"] = ("Accessory '{0}' không tồn tại.", "Accessory '{0}' does not exist."),
        ["Build_AccessoryUnavailable"] = ("Accessory '{0}' không còn khả dụng.", "Accessory '{0}' is no longer available."),
        ["Build_AccessoryTargetUnknown"] = ("Accessory '{0}' có target component không xác định.", "Accessory '{0}' has an unknown target component."),
        ["Build_ModSwitchExceed"] = ("Tổng số switch cho mod '{0}' là {1}, vượt quá số switch đã đặt {2}.", "Total switches for mod '{0}' is {1}, exceeding the {2} switches ordered."),

        // ===== Build request snapshot (seller view) =====
        ["Snapshot_Empty"] = ("Snapshot build chưa có dữ liệu.", "Build snapshot has no data."),
        ["Snapshot_Status"] = ("Trạng thái", "Status"),
        ["Snapshot_NoiseRequirement"] = ("Yêu cầu độ ồn", "Noise requirement"),
        ["Snapshot_Total"] = ("Tổng giá", "Total price"),
        ["Snapshot_Notes"] = ("Ghi chú", "Notes"),
        ["Snapshot_NoKit"] = ("Không có kit trong snapshot.", "No kit in the snapshot."),
        ["Snapshot_SwitchNeeded"] = ("Số switch cần", "Switches needed"),
        ["Snapshot_Items"] = ("Linh kiện:", "Parts:"),
        ["Snapshot_NoItems"] = ("Chưa có linh kiện.", "No parts yet."),
        ["Snapshot_KitPrice"] = ("Giá kit", "Kit price"),
        ["Snapshot_Included"] = ("Đã gồm", "Included"),
        ["Snapshot_Mods"] = ("Mod:", "Mods:"),
        ["Snapshot_Note"] = ("Ghi chú", "Note"),
        ["Snapshot_SellerPhone"] = ("SĐT seller", "Seller phone"),
        ["Snapshot_SellerAddress"] = ("Địa chỉ seller", "Seller address"),

        // ===== Seller dashboard =====
        ["Seller_Title"] = ("Bảng điều khiển Seller", "Seller dashboard"),
        ["Seller_Subtitle"] = ("Xử lý request build được gán cho seller.", "Handle build requests assigned to the seller."),
        ["Seller_Task1"] = ("Xem danh sách request mới", "Review the list of new requests"),
        ["Seller_Task2"] = ("Mở chi tiết build snapshot", "Open the build snapshot details"),
        ["Seller_Task3"] = ("Cập nhật trạng thái request", "Update request status"),
        ["Seller_Task4"] = ("Chat với buyer và admin", "Chat with buyers and admins"),
        ["Seller_RequestsRefreshed"] = ("Đã làm mới request.", "Requests refreshed."),
        ["Seller_SelectRequestForSnapshot"] = ("Chọn request để xem snapshot build.", "Select a request to view the build snapshot."),
        ["Seller_ChartUpdated"] = ("Đã cập nhật biểu đồ.", "Chart updated."),
        ["Seller_NewRequestRealtime"] = ("Có request mới (realtime).", "New request received (realtime)."),
        ["Seller_SelectRequestFirst"] = ("Chọn request trước.", "Select a request first."),
        ["Seller_RequestStatusUpdated"] = ("Đã cập nhật request sang {0}.", "Request updated to {0}."),
        ["Seller_Workspace"] = ("Không gian Seller", "Seller workspace"),
        ["Seller_NavRequest"] = ("Request", "Requests"),
        ["Seller_NavAnalytics"] = ("Phân tích", "Analytics"),
        ["Seller_AssignedRequests"] = ("Request được gán", "Assigned requests"),
        ["Seller_EmptyRequestsTitle"] = ("Chưa có request được gán", "No assigned requests"),
        ["Seller_EmptyRequestsText"] = ("Request mới từ buyer sẽ xuất hiện tại đây.", "New buyer requests will appear here."),
        ["Seller_Accept"] = ("Chấp nhận", "Accept"),
        ["Seller_InProgress"] = ("Đang làm", "In progress"),
        ["Seller_Complete"] = ("Hoàn thành", "Complete"),
        ["Seller_Cancel"] = ("Hủy", "Cancel"),
        ["Seller_SnapshotTitle"] = ("Snapshot build", "Build snapshot"),
        ["Seller_KpiRevenue"] = ("Doanh thu (USD)", "Revenue (USD)"),
        ["Seller_KpiProducts"] = ("Sản phẩm", "Products"),
        ["Seller_KpiCustomers"] = ("Khách hàng", "Customers"),
        ["Seller_KpiInProgress"] = ("Đang xử lý", "In progress"),
        ["Seller_KpiAvgCompletion"] = ("TG hoàn thành TB", "Avg. completion time"),
        ["Seller_RevenueOrders"] = ("Doanh thu & số đơn", "Revenue & orders"),
        ["Seller_StatusRatio"] = ("Tỉ lệ trạng thái", "Status breakdown"),
        ["Seller_TopKit"] = ("Top kit", "Top kits"),
        ["Seller_EmptyKitsTitle"] = ("Chưa có kit hoàn thành", "No completed kits"),
        ["Seller_EmptyKitsText"] = ("Hoàn thành đơn đầu tiên để bắt đầu thống kê.", "Complete your first order to start tracking stats."),

        // ===== Admin dashboard (ViewModel) =====
        ["Admin_Title"] = ("Bảng điều khiển Admin", "Admin dashboard"),
        ["Admin_Subtitle"] = ("Quản lý user, seller và danh mục kit-based.", "Manage users, sellers and the kit-based catalog."),
        ["Admin_Task1"] = ("Quản lý user và trạng thái active", "Manage users and active status"),
        ["Admin_Task2"] = ("Quản lý seller profile và verify", "Manage seller profiles and verification"),
        ["Admin_Task3"] = ("Quản lý kit/switch/keycap/stabilizer/accessory", "Manage kit/switch/keycap/stabilizer/accessory"),
        ["Admin_Task4"] = ("Xem audit log và chat với seller", "Review the audit log and chat with sellers"),
        ["Admin_RefreshedDashboard"] = ("Đã làm mới bảng điều khiển admin.", "Admin dashboard refreshed."),
        ["Admin_RefreshedUsers"] = ("Đã làm mới danh sách user.", "Users refreshed."),
        ["Admin_UserBanned"] = ("Đã khóa user.", "User banned."),
        ["Admin_UserUnbanned"] = ("Đã mở khóa user.", "User unbanned."),
        ["Admin_RoleChanged"] = ("Đã đổi vai trò user.", "User role changed."),
        ["Admin_RefreshedSellers"] = ("Đã làm mới danh sách seller.", "Sellers refreshed."),
        ["Admin_SellerProfileSaved"] = ("Đã lưu hồ sơ seller.", "Seller profile saved."),
        ["Admin_SellerVerified"] = ("Đã verify seller.", "Seller verified."),
        ["Admin_SellerUnverified"] = ("Đã bỏ verify seller.", "Seller unverified."),
        ["Admin_RefreshedCatalog"] = ("Đã làm mới brand.", "Brands refreshed."),
        ["Admin_BrandSaved"] = ("Đã lưu brand.", "Brand saved."),
        ["Admin_BrandDeleted"] = ("Đã xóa brand.", "Brand deleted."),
        ["Admin_LayoutSaved"] = ("Đã lưu layout.", "Layout saved."),
        ["Admin_RefreshedComponents"] = ("Đã làm mới linh kiện.", "Components refreshed."),
        ["Admin_ComponentSaved"] = ("Đã lưu linh kiện.", "Component saved."),
        ["Admin_ComponentHidden"] = ("Đã ẩn linh kiện.", "Component hidden."),
        ["Admin_ComponentRestored"] = ("Đã khôi phục linh kiện.", "Component restored."),
        ["Admin_RefreshedAudit"] = ("Đã làm mới audit log.", "Audit log refreshed."),
        ["Admin_RefreshedApplications"] = ("Đã làm mới đơn seller.", "Seller applications refreshed."),
        ["Admin_ApplicationApproved"] = ("Đã duyệt đơn seller.", "Seller application approved."),
        ["Admin_ApplicationRejected"] = ("Đã từ chối đơn seller.", "Seller application rejected."),
        ["Admin_ChartUpdated"] = ("Đã cập nhật biểu đồ.", "Chart updated."),
        ["Admin_SelectApplicationFirst"] = ("Chọn đơn trước.", "Select an application first."),
        ["Admin_SelectUserFirst"] = ("Chọn user trước.", "Select a user first."),
        ["Admin_SelectSellerUserFirst"] = ("Chọn seller user trước.", "Select a seller user first."),
        ["Admin_SelectSellerFirst"] = ("Chọn seller trước.", "Select a seller first."),
        ["Admin_SelectComponentFirst"] = ("Chọn linh kiện trước.", "Select a component first."),
        ["Admin_SelectBrandFirst"] = ("Chọn brand trước.", "Select a brand first."),

        // ===== Admin dashboard (XAML) =====
        ["Admin_Workspace"] = ("Không gian Admin", "Admin workspace"),
        ["Admin_NavOverview"] = ("Tổng quan", "Overview"),
        ["Admin_NavUsers"] = ("Người dùng", "Users"),
        ["Admin_NavSeller"] = ("Seller", "Sellers"),
        ["Admin_NavApplications"] = ("Đơn xin Seller", "Seller applications"),
        ["Admin_NavBrandLayout"] = ("Brand", "Brand"),
        ["Admin_NavComponents"] = ("Linh kiện", "Components"),
        ["Admin_NavAudit"] = ("Audit log", "Audit log"),
        ["Admin_KpiUsers"] = ("Users", "Users"),
        ["Admin_KpiSellers"] = ("Sellers", "Sellers"),
        ["Admin_KpiComponents"] = ("Linh kiện", "Components"),
        ["Admin_KpiRequests"] = ("Requests", "Requests"),
        ["Admin_RevenueAllPlatform"] = ("Doanh thu toàn sàn (USD)", "Platform revenue (USD)"),
        ["Admin_CompletedOrders"] = ("Đơn hoàn thành", "Completed orders"),
        ["Admin_VerifiedSellers"] = ("Verified sellers", "Verified sellers"),
        ["Admin_Builds"] = ("Builds", "Builds"),
        ["Admin_TotalUsersLabel"] = ("Tổng user:", "Total users:"),
        ["Admin_RevenueOverTime"] = ("Doanh thu theo thời gian", "Revenue over time"),
        ["Admin_OrdersByStatus"] = ("Đơn theo trạng thái", "Orders by status"),
        ["Admin_TopSellersByRevenue"] = ("Top seller theo doanh thu", "Top sellers by revenue"),
        ["Admin_EmptyUsersTitle"] = ("Chưa có user", "No users"),
        ["Admin_EmptyUsersText"] = ("Chạy seed hoặc đăng ký buyer mới để có dữ liệu.", "Run the seed or register a new buyer to get data."),
        ["Admin_Actions"] = ("Thao tác", "Actions"),
        ["Admin_ChangeRole"] = ("Đổi vai trò", "Change role"),
        ["Admin_BanUser"] = ("Khóa user", "Ban user"),
        ["Admin_UnbanUser"] = ("Mở khóa", "Unban"),
        ["Admin_ColVerify"] = ("VERIFY", "VERIFY"),
        ["Admin_EmptySellersTitle"] = ("Chưa có seller profile", "No seller profiles"),
        ["Admin_EmptySellersText"] = ("Tạo seller user/profile hoặc chạy seed demo.", "Create a seller user/profile or run the demo seed."),
        ["Admin_SellerProfile"] = ("Hồ sơ seller", "Seller profile"),
        ["Admin_SaveProfile"] = ("Lưu hồ sơ", "Save profile"),
        ["Admin_Verify"] = ("Verify", "Verify"),
        ["Admin_Unverify"] = ("Unverify", "Unverify"),
        ["Admin_Brands"] = ("Brands", "Brands"),
        ["Admin_EmptyBrandsTitle"] = ("Chưa có brand", "No brands"),
        ["Admin_EmptyBrandsText"] = ("Nhập brand mới bên dưới rồi lưu.", "Enter a new brand below, then save."),
        ["Admin_BrandName"] = ("Tên brand", "Brand name"),
        ["Admin_Country"] = ("Quốc gia", "Country"),
        ["Admin_SaveBrand"] = ("Lưu brand", "Save brand"),
        ["Admin_DeleteBrand"] = ("Xóa brand", "Delete brand"),
        ["Admin_Layouts"] = ("Layouts", "Layouts"),
        ["Admin_EmptyLayoutsTitle"] = ("Chưa có layout", "No layouts"),
        ["Admin_EmptyLayoutsText"] = ("Nhập layout mới bên dưới rồi lưu.", "Enter a new layout below, then save."),
        ["Admin_LayoutId"] = ("Layout id", "Layout id"),
        ["Admin_Name"] = ("Tên", "Name"),
        ["Admin_FormFactor"] = ("Form factor", "Form factor"),
        ["Admin_KeyCount"] = ("Key count", "Key count"),
        ["Admin_SaveLayout"] = ("Lưu layout", "Save layout"),
        ["Admin_ColName"] = ("TÊN", "NAME"),
        ["Admin_ColId"] = ("ID", "ID"),
        ["Admin_ColPrice"] = ("GIÁ (USD)", "PRICE (USD)"),
        ["Admin_ColAvailable"] = ("CÓ SẴN", "AVAILABLE"),
        ["Admin_EmptyComponentsTitle"] = ("Chưa có linh kiện", "No components"),
        ["Admin_EmptyComponentsText"] = ("Chọn loại linh kiện và tạo item mới bằng editor.", "Pick a component type and create a new item with the editor."),
        ["Admin_Hide"] = ("Ẩn", "Hide"),
        ["Admin_Restore"] = ("Khôi phục", "Restore"),
        ["Admin_ComponentEditor"] = ("Editor linh kiện", "Component editor"),
        ["Admin_ComponentId"] = ("Component id", "Component id"),
        ["Admin_PriceUsd"] = ("Giá (USD)", "Price (USD)"),
        ["Admin_AvailableCheckbox"] = ("Khả dụng", "Available"),
        ["Admin_Layout"] = ("Layout", "Layout"),
        ["Admin_PcbTechnology"] = ("PCB technology", "PCB technology"),
        ["Admin_SwitchMount"] = ("Switch mount", "Switch mount"),
        ["Admin_RequiredSwitchQty"] = ("Required switch quantity", "Required switch quantity"),
        ["Admin_IncludedParts"] = ("Included parts", "Included parts"),
        ["Admin_SwitchTechnology"] = ("Switch technology", "Switch technology"),
        ["Admin_MountType"] = ("Mount type", "Mount type"),
        ["Admin_SwitchType"] = ("Switch type", "Switch type"),
        ["Admin_ActuationForce"] = ("Actuation force (g)", "Actuation force (g)"),
        ["Admin_SupportedFormFactor"] = ("Supported form factor", "Supported form factor"),
        ["Admin_Profile"] = ("Profile", "Profile"),
        ["Admin_Material"] = ("Material", "Material"),
        ["Admin_SupportedLayouts"] = ("Supported layouts", "Supported layouts"),
        ["Admin_AccessoryType"] = ("Accessory type", "Accessory type"),
        ["Admin_TargetComponent"] = ("Target component", "Target component"),
        ["Admin_Brand"] = ("Brand", "Brand"),
        ["Admin_SaveComponent"] = ("Lưu linh kiện", "Save component"),
        ["Admin_RefreshAudit"] = ("Làm mới audit", "Refresh audit"),
        ["Admin_ColAction"] = ("ACTION", "ACTION"),
        ["Admin_ColTable"] = ("BẢNG", "TABLE"),
        ["Admin_ColRecord"] = ("RECORD", "RECORD"),
        ["Admin_ColTime"] = ("THỜI GIAN", "TIME"),
        ["Admin_EmptyAuditTitle"] = ("Chưa có audit log", "No audit logs"),
        ["Admin_EmptyAuditText"] = ("Các thao tác admin sẽ được ghi lại tại đây.", "Admin actions will be logged here."),
        ["Admin_ApplicationsTitle"] = ("Đơn xin làm Seller", "Seller applications"),
        ["Admin_ColApplicant"] = ("NGƯỜI NỘP", "APPLICANT"),
        ["Admin_ApplicationDetail"] = ("Chi tiết đơn", "Application details"),
        ["Admin_Applicant"] = ("Người nộp", "Applicant"),
        ["Admin_ReviewNoteOptional"] = ("Ghi chú duyệt (không bắt buộc)", "Review note (optional)"),
        ["Admin_Approve"] = ("Chấp nhận", "Approve"),
        ["Admin_Reject"] = ("Từ chối", "Reject"),

        // ===== Service-level validation / errors (thrown, shown via catch) =====
        ["Service_InvalidBuyer"] = ("Buyer không hợp lệ.", "Invalid buyer."),
        ["Service_RequestNotExist"] = ("Request không tồn tại.", "Request does not exist."),
        ["Service_RequestNotOwned"] = ("Request không thuộc seller hiện tại.", "This request does not belong to the current seller."),
        ["Service_InvalidTransition"] = ("Không thể chuyển request từ {0} sang {1}.", "Cannot move request from {0} to {1}."),
        ["Service_QcRequiredBeforeComplete"] = ("Cần chạy QC và có kết quả đạt hoặc chỉ còn cảnh báo trước khi hoàn thành request.", "Run QC with a passed or warning-only result before completing the request."),
        ["Service_OnlySellerProfile"] = ("Chỉ user role Seller mới có seller profile.", "Only Seller-role users can have a seller profile."),
        ["Service_OnlySellerVerify"] = ("Chỉ user role Seller mới được verify.", "Only Seller-role users can be verified."),
        ["Service_CannotVerifyLocked"] = ("Không thể verify seller đang bị khóa.", "Cannot verify a locked seller."),
        ["Service_CreateProfileBeforeVerify"] = ("Hãy tạo seller profile trước khi verify.", "Create a seller profile before verifying."),
        ["Service_SellerProfileNotFoundAfterUpdate"] = ("Không tìm thấy seller profile sau khi cập nhật.", "Seller profile not found after the update."),
        ["Service_ComponentNotFound"] = ("Không tìm thấy linh kiện.", "Component not found."),
        ["Service_ComponentNotFoundAfterUpdate"] = ("Không tìm thấy linh kiện sau khi cập nhật.", "Component not found after the update."),
        ["Service_OnlyActiveAdmin"] = ("Chỉ admin active mới được thực hiện thao tác này.", "Only an active admin can perform this action."),
        ["Service_UserNotFound"] = ("Không tìm thấy user.", "User not found."),
        ["Service_ComponentPriceNegative"] = ("Giá linh kiện không được âm.", "Component price cannot be negative."),
        ["Service_BrandNotExist"] = ("Brand không tồn tại.", "Brand does not exist."),
        ["Service_BrandInUse"] = ("Không thể xóa brand vì đang được kit, switch, keycap hoặc stabilizer sử dụng.", "Cannot delete this brand because it is used by a kit, switch, keycap set, or stabilizer."),
        ["Service_LayoutNotExist"] = ("Layout không tồn tại: {0}", "Layout does not exist: {0}"),
        ["Service_FieldRequired"] = ("{0} không được rỗng.", "{0} cannot be empty."),
        ["Service_AccountLockedNoApply"] = ("Tài khoản đang bị khóa, không thể nộp đơn.", "Your account is locked; you cannot apply."),
        ["Service_OnlyBuyerApply"] = ("Chỉ tài khoản Buyer mới được nộp đơn lên Seller.", "Only Buyer accounts can apply to become a seller."),
        ["Service_AlreadyPendingApplication"] = ("Bạn đã có một đơn đang chờ duyệt.", "You already have a pending application."),
        ["Service_ApplicationNotFound"] = ("Không tìm thấy đơn.", "Application not found."),
        ["Service_ApplicationProcessed"] = ("Đơn đã được xử lý.", "This application has already been processed."),
        ["Service_CannotApproveLocked"] = ("Không thể duyệt: tài khoản người nộp đang bị khóa.", "Cannot approve: the applicant's account is locked."),
        ["Service_CannotApproveNotBuyer"] = ("Không thể duyệt: người nộp hiện không còn là Buyer.", "Cannot approve: the applicant is no longer a Buyer."),
        ["Service_CannotApproveNotActiveBuyer"] = ("Không thể duyệt: người nộp hiện không còn là Buyer active.", "Cannot approve: the applicant is no longer an active Buyer."),
        ["Service_OnlyActiveAdminReview"] = ("Chỉ admin active mới được duyệt đơn seller.", "Only an active admin can review seller applications."),
        ["Service_FieldTooLong"] = ("{0} không được vượt quá {1} ký tự.", "{0} cannot exceed {1} characters."),
        ["Service_InvalidUser"] = ("User không hợp lệ.", "Invalid user."),
        ["Service_SellerBuyerSame"] = ("Seller và buyer không được trùng nhau.", "Seller and buyer cannot be the same."),
        ["Service_MessageEmpty"] = ("Nội dung tin nhắn không được rỗng.", "Message content cannot be empty."),
        ["Service_MessageTooLong"] = ("Tin nhắn không được vượt quá {0} ký tự.", "Message cannot exceed {0} characters."),
        ["Service_InvalidConversation"] = ("Conversation không hợp lệ.", "Invalid conversation."),
        ["Service_ConversationNotExist"] = ("Conversation không tồn tại.", "Conversation does not exist."),
        ["Service_SellerNotVerified"] = ("Seller chưa được verified.", "Seller is not verified yet."),
        ["Service_InvalidEntity"] = ("{0} không hợp lệ.", "Invalid {0}."),
        ["Service_EntityNotFound"] = ("Không tìm thấy {0}.", "{0} not found."),
        ["Service_EntityLocked"] = ("{0} đang bị khóa.", "{0} is locked."),
        ["Service_UserNotRole"] = ("User không phải {0}.", "User is not {0}."),
        ["Service_BuildNotReady"] = ("Build chưa đủ cấu hình để gửi request.", "The build is not complete enough to send a request."),
        ["Service_SellerNotVerifiedOrInactive"] = ("Seller chưa verified hoặc bị inactive.", "Seller is not verified or is inactive."),
        ["Service_BuildHasActiveRequest"] = ("Build này đang có request active; không thể gửi thêm.", "This build already has an active request; you can't send another."),
        ["Service_ConversationParticipants"] = ("Conversation phải có đúng một buyer hoặc admin.", "A conversation must have exactly one buyer or admin."),
        ["Service_NotConversationParticipant"] = ("User không thuộc conversation này.", "You are not a participant in this conversation."),
        ["Service_SellerNoProfile"] = ("Seller chưa có profile.", "Seller has no profile yet."),
        ["Service_AdminCannotLockSelf"] = ("Admin không thể khóa chính tài khoản đang dùng.", "An admin cannot lock the account they are signed in with."),
        ["Service_AdminCannotChangeOwnRole"] = ("Admin không thể đổi vai trò của chính mình khỏi Admin.", "An admin cannot change their own role away from Admin."),
        ["Service_SellerProfileFieldsRequired"] = ("Nhập đầy đủ tên shop, số điện thoại và địa chỉ.", "Enter the shop name, phone and address."),
        ["Service_BrandNameRequired"] = ("Nhập brand name.", "Enter a brand name."),
        ["Service_LayoutFieldsRequired"] = ("Nhập đầy đủ layout id, name và form factor.", "Enter the layout id, name and form factor."),
        ["Service_KeyCountPositive"] = ("Key count phải lớn hơn 0.", "Key count must be greater than 0."),
        ["Service_ComponentIdRequired"] = ("Nhập component id.", "Enter a component id."),
        ["Service_ComponentNameRequired"] = ("Nhập tên linh kiện.", "Enter a component name."),
        ["Service_BrandIdPositive"] = ("BrandId phải lớn hơn 0.", "BrandId must be greater than 0."),
        ["Service_RequiredSwitchQtyPositive"] = ("Required switch quantity phải lớn hơn 0.", "Required switch quantity must be greater than 0."),
        ["Service_ActuationForcePositive"] = ("Actuation force phải lớn hơn 0.", "Actuation force must be greater than 0."),
        ["Service_TargetComponentInvalid"] = ("Target component phải là Switch, Stabilizer, Kit hoặc General.", "Target component must be Switch, Stabilizer, Kit or General."),
        ["Service_ReviewNoteField"] = ("ghi chú duyệt", "review note"),

        // ===== Analytics charts (series / axis names baked into LiveCharts objects) =====
        ["Chart_Revenue"] = ("Doanh thu (USD)", "Revenue (USD)"),
        ["Chart_Orders"] = ("Số đơn", "Orders"),

        // ===== Diagnostics (error dialog / infrastructure messages) =====
        ["Error_DialogTitle"] = ("Đã xảy ra lỗi ({0})", "An error occurred ({0})"),
        ["Error_LogHint"] = ("Chi tiết kỹ thuật đã được ghi vào file log.\nMở file log để xem chi tiết?", "Technical details were written to the log file.\nOpen the log file to view them?"),
        ["Error_DatabaseUnavailable"] = ("Không thể truy cập cơ sở dữ liệu. Kiểm tra SQL Server và chuỗi kết nối rồi thử lại.", "Cannot reach the database. Check SQL Server and the connection string, then try again."),

        // ===== END OF TABLE (insert new keys above this line) =====
    };
}
